server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://rm-2zer82h49au9jasm72o.mysql.rds.aliyuncs.com:3306/aii?characterEncoding=utf8
    username: user_01
    password: 123456aA
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
  cache:
    cache-names: resources
    caffeine:
      spec: initialCapacity=5,maximumSize=500,expireAfterWrite=3600s

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml


aii:
  # 请求域配置
  allow-origin: http://localhost:8080


shiro:
  annotations:
    # 权限注解
    enabled: true